{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "local-ai.fullname" . }}
  labels:
    {{- include "local-ai.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "local-ai.name" . }}
  endpoints:
    - port: http
      path: /metrics
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeClass }}
      scrapeClass: {{ .Values.serviceMonitor.scrapeClass }}
      {{- end }}
  {{- if .Values.serviceMonitor.namespace }}
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitor.namespace }}
  {{- else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
{{- end }}
